// This code was generated by: 
// https://github.com/recolude/swagger-unity-codegen
// Issues and PRs welcome :)

namespace Recolude
{

	/// <summary>
	/// A collection of parameters that different services use to make calls 
	/// to Recolude. 
	/// </summary>
    public interface Config
    {

        // The base URL to which the endpoint paths are appended
        string BasePath { get; }

        // ApiKeyAuth is a API Key 'X-API-KEY' found in a request's header
        string ApiKeyAuth { get; }

        // CognitoAuth is a API Key 'Authorization' found in a request's header
        string CognitoAuth { get; }

        // DevKeyAuth is a API Key 'X-DEV-KEY' found in a request's header
        string DevKeyAuth { get; }

    }

}